// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPropertySetter creates a new instance of MockPropertySetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPropertySetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPropertySetter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPropertySetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPropertySetter is an autogenerated mock type for the PropertySetter type
type MockPropertySetter struct {
	mock.Mock
}

type MockPropertySetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPropertySetter) EXPECT() *MockPropertySetter_Expecter {
	return &MockPropertySetter_Expecter{mock: &_m.Mock}
}

// SetMust provides a mock function for the type MockPropertySetter
func (_mock *MockPropertySetter) SetMust(iface string, property string, value any) {
	_mock.Called(iface, property, value)
	return
}

// MockPropertySetter_SetMust_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMust'
type MockPropertySetter_SetMust_Call struct {
	*mock.Call
}

// SetMust is a helper method to define mock.On call
//   - iface string
//   - property string
//   - value any
func (_e *MockPropertySetter_Expecter) SetMust(iface any, property any, value any) *MockPropertySetter_SetMust_Call {
	return &MockPropertySetter_SetMust_Call{Call: _e.mock.On("SetMust", iface, property, value)}
}

func (_c *MockPropertySetter_SetMust_Call) Run(run func(iface string, property string, value any)) *MockPropertySetter_SetMust_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPropertySetter_SetMust_Call) Return() *MockPropertySetter_SetMust_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPropertySetter_SetMust_Call) RunAndReturn(run func(iface string, property string, value any)) *MockPropertySetter_SetMust_Call {
	_c.Run(run)
	return _c
}
