// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// NotifyTest provides a mock function for the type MockSender
func (_mock *MockSender) NotifyTest(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NotifyTest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSender_NotifyTest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyTest'
type MockSender_NotifyTest_Call struct {
	*mock.Call
}

// NotifyTest is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSender_Expecter) NotifyTest(ctx any) *MockSender_NotifyTest_Call {
	return &MockSender_NotifyTest_Call{Call: _e.mock.On("NotifyTest", ctx)}
}

func (_c *MockSender_NotifyTest_Call) Run(run func(ctx context.Context)) *MockSender_NotifyTest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSender_NotifyTest_Call) Return(err error) *MockSender_NotifyTest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSender_NotifyTest_Call) RunAndReturn(run func(ctx context.Context) error) *MockSender_NotifyTest_Call {
	_c.Call.Return(run)
	return _c
}
