// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/godbus/dbus/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCaller creates a new instance of MockCaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCaller {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCaller is an autogenerated mock type for the Caller type
type MockCaller struct {
	mock.Mock
}

type MockCaller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCaller) EXPECT() *MockCaller_Expecter {
	return &MockCaller_Expecter{mock: &_m.Mock}
}

// CallWithContext provides a mock function for the type MockCaller
func (_mock *MockCaller) CallWithContext(ctx context.Context, method string, flags dbus.Flags, args ...any) *dbus.Call {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, method, flags, args)
	} else {
		tmpRet = _mock.Called(ctx, method, flags)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CallWithContext")
	}

	var r0 *dbus.Call
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dbus.Flags, ...any) *dbus.Call); ok {
		r0 = returnFunc(ctx, method, flags, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbus.Call)
		}
	}
	return r0
}

// MockCaller_CallWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallWithContext'
type MockCaller_CallWithContext_Call struct {
	*mock.Call
}

// CallWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - flags dbus.Flags
//   - args ...any
func (_e *MockCaller_Expecter) CallWithContext(ctx any, method any, flags any, args ...any) *MockCaller_CallWithContext_Call {
	return &MockCaller_CallWithContext_Call{Call: _e.mock.On("CallWithContext",
		append([]any{ctx, method, flags}, args...)...)}
}

func (_c *MockCaller_CallWithContext_Call) Run(run func(ctx context.Context, method string, flags dbus.Flags, args ...any)) *MockCaller_CallWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 dbus.Flags
		if args[2] != nil {
			arg2 = args[2].(dbus.Flags)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockCaller_CallWithContext_Call) Return(call *dbus.Call) *MockCaller_CallWithContext_Call {
	_c.Call.Return(call)
	return _c
}

func (_c *MockCaller_CallWithContext_Call) RunAndReturn(run func(ctx context.Context, method string, flags dbus.Flags, args ...any) *dbus.Call) *MockCaller_CallWithContext_Call {
	_c.Call.Return(run)
	return _c
}
