// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/clankerwatch/internal/config"
	"github.com/nicholas-fedor/clankerwatch/internal/daemon"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReporter creates a new instance of MockReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReporter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReporter is an autogenerated mock type for the Reporter type
type MockReporter struct {
	mock.Mock
}

type MockReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReporter) EXPECT() *MockReporter_Expecter {
	return &MockReporter_Expecter{mock: &_m.Mock}
}

// Status provides a mock function for the type MockReporter
func (_mock *MockReporter) Status(ctx context.Context, cfg config.Config) daemon.Report {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 daemon.Report
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Config) daemon.Report); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Get(0).(daemon.Report)
	}
	return r0
}

// MockReporter_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockReporter_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg config.Config
func (_e *MockReporter_Expecter) Status(ctx any, cfg any) *MockReporter_Status_Call {
	return &MockReporter_Status_Call{Call: _e.mock.On("Status", ctx, cfg)}
}

func (_c *MockReporter_Status_Call) Run(run func(ctx context.Context, cfg config.Config)) *MockReporter_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.Config
		if args[1] != nil {
			arg1 = args[1].(config.Config)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReporter_Status_Call) Return(report daemon.Report) *MockReporter_Status_Call {
	_c.Call.Return(report)
	return _c
}

func (_c *MockReporter_Status_Call) RunAndReturn(run func(ctx context.Context, cfg config.Config) daemon.Report) *MockReporter_Status_Call {
	_c.Call.Return(run)
	return _c
}
