// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/clankerwatch/internal/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServer creates a new instance of MockServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

type MockServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServer) EXPECT() *MockServer_Expecter {
	return &MockServer_Expecter{mock: &_m.Mock}
}

// Serve provides a mock function for the type MockServer
func (_mock *MockServer) Serve(ctx context.Context, cfg config.Config, reload func() (config.Config, error)) error {
	ret := _mock.Called(ctx, cfg, reload)

	if len(ret) == 0 {
		panic("no return value specified for Serve")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Config, func() (config.Config, error)) error); ok {
		r0 = returnFunc(ctx, cfg, reload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServer_Serve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serve'
type MockServer_Serve_Call struct {
	*mock.Call
}

// Serve is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg config.Config
//   - reload func() (config.Config, error)
func (_e *MockServer_Expecter) Serve(ctx any, cfg any, reload any) *MockServer_Serve_Call {
	return &MockServer_Serve_Call{Call: _e.mock.On("Serve", ctx, cfg, reload)}
}

func (_c *MockServer_Serve_Call) Run(run func(ctx context.Context, cfg config.Config, reload func() (config.Config, error))) *MockServer_Serve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.Config
		if args[1] != nil {
			arg1 = args[1].(config.Config)
		}
		var arg2 func() (config.Config, error)
		if args[2] != nil {
			arg2 = args[2].(func() (config.Config, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServer_Serve_Call) Return(err error) *MockServer_Serve_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServer_Serve_Call) RunAndReturn(run func(ctx context.Context, cfg config.Config, reload func() (config.Config, error)) error) *MockServer_Serve_Call {
	_c.Call.Return(run)
	return _c
}
