// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"log/slog"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLevelSetter creates a new instance of MockLevelSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLevelSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLevelSetter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockLevelSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockLevelSetter is an autogenerated mock type for the LevelSetter type
type MockLevelSetter struct {
	mock.Mock
}

type MockLevelSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLevelSetter) EXPECT() *MockLevelSetter_Expecter {
	return &MockLevelSetter_Expecter{mock: &_m.Mock}
}

// SetLevel provides a mock function for the type MockLevelSetter
func (_mock *MockLevelSetter) SetLevel(level slog.Level) {
	_mock.Called(level)
	return
}

// MockLevelSetter_SetLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLevel'
type MockLevelSetter_SetLevel_Call struct {
	*mock.Call
}

// SetLevel is a helper method to define mock.On call
//   - level slog.Level
func (_e *MockLevelSetter_Expecter) SetLevel(level any) *MockLevelSetter_SetLevel_Call {
	return &MockLevelSetter_SetLevel_Call{Call: _e.mock.On("SetLevel", level)}
}

func (_c *MockLevelSetter_SetLevel_Call) Run(run func(level slog.Level)) *MockLevelSetter_SetLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 slog.Level
		if args[0] != nil {
			arg0 = args[0].(slog.Level)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLevelSetter_SetLevel_Call) Return() *MockLevelSetter_SetLevel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLevelSetter_SetLevel_Call) RunAndReturn(run func(level slog.Level)) *MockLevelSetter_SetLevel_Call {
	_c.Run(run)
	return _c
}
