// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockActivitySource creates a new instance of MockActivitySource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivitySource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivitySource {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockActivitySource{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockActivitySource is an autogenerated mock type for the ActivitySource type
type MockActivitySource struct {
	mock.Mock
}

type MockActivitySource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivitySource) EXPECT() *MockActivitySource_Expecter {
	return &MockActivitySource_Expecter{mock: &_m.Mock}
}

// Active provides a mock function for the type MockActivitySource
func (_mock *MockActivitySource) Active(now time.Time) bool {
	ret := _mock.Called(now)

	if len(ret) == 0 {
		panic("no return value specified for Active")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(time.Time) bool); ok {
		r0 = returnFunc(now)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockActivitySource_Active_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Active'
type MockActivitySource_Active_Call struct {
	*mock.Call
}

// Active is a helper method to define mock.On call
//   - now time.Time
func (_e *MockActivitySource_Expecter) Active(now any) *MockActivitySource_Active_Call {
	return &MockActivitySource_Active_Call{Call: _e.mock.On("Active", now)}
}

func (_c *MockActivitySource_Active_Call) Run(run func(now time.Time)) *MockActivitySource_Active_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActivitySource_Active_Call) Return(b bool) *MockActivitySource_Active_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockActivitySource_Active_Call) RunAndReturn(run func(now time.Time) bool) *MockActivitySource_Active_Call {
	_c.Call.Return(run)
	return _c
}
