// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nicholas-fedor/clankerwatch/internal/claudecode"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCredentialsSource creates a new instance of MockCredentialsSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialsSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialsSource {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCredentialsSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCredentialsSource is an autogenerated mock type for the CredentialsSource type
type MockCredentialsSource struct {
	mock.Mock
}

type MockCredentialsSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialsSource) EXPECT() *MockCredentialsSource_Expecter {
	return &MockCredentialsSource_Expecter{mock: &_m.Mock}
}

// Read provides a mock function for the type MockCredentialsSource
func (_mock *MockCredentialsSource) Read() (claudecode.OAuth, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 claudecode.OAuth
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (claudecode.OAuth, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() claudecode.OAuth); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(claudecode.OAuth)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCredentialsSource_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockCredentialsSource_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *MockCredentialsSource_Expecter) Read() *MockCredentialsSource_Read_Call {
	return &MockCredentialsSource_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *MockCredentialsSource_Read_Call) Run(run func()) *MockCredentialsSource_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCredentialsSource_Read_Call) Return(oAuth claudecode.OAuth, err error) *MockCredentialsSource_Read_Call {
	_c.Call.Return(oAuth, err)
	return _c
}

func (_c *MockCredentialsSource_Read_Call) RunAndReturn(run func() (claudecode.OAuth, error)) *MockCredentialsSource_Read_Call {
	_c.Call.Return(run)
	return _c
}
