// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nicholas-fedor/clankerwatch/internal/claudecode"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGlobalSource creates a new instance of MockGlobalSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGlobalSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGlobalSource {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGlobalSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGlobalSource is an autogenerated mock type for the GlobalSource type
type MockGlobalSource struct {
	mock.Mock
}

type MockGlobalSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGlobalSource) EXPECT() *MockGlobalSource_Expecter {
	return &MockGlobalSource_Expecter{mock: &_m.Mock}
}

// Read provides a mock function for the type MockGlobalSource
func (_mock *MockGlobalSource) Read() (claudecode.GlobalState, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 claudecode.GlobalState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (claudecode.GlobalState, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() claudecode.GlobalState); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(claudecode.GlobalState)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGlobalSource_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockGlobalSource_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *MockGlobalSource_Expecter) Read() *MockGlobalSource_Read_Call {
	return &MockGlobalSource_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *MockGlobalSource_Read_Call) Run(run func()) *MockGlobalSource_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGlobalSource_Read_Call) Return(globalState claudecode.GlobalState, err error) *MockGlobalSource_Read_Call {
	_c.Call.Return(globalState, err)
	return _c
}

func (_c *MockGlobalSource_Read_Call) RunAndReturn(run func() (claudecode.GlobalState, error)) *MockGlobalSource_Read_Call {
	_c.Call.Return(run)
	return _c
}
