// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/clankerwatch/internal/notify"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockNotifier
func (_mock *MockNotifier) Send(ctx context.Context, message notify.Message) (uint32, error) {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, notify.Message) (uint32, error)); ok {
		return returnFunc(ctx, message)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, notify.Message) uint32); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Get(0).(uint32)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, notify.Message) error); ok {
		r1 = returnFunc(ctx, message)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotifier_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockNotifier_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - message notify.Message
func (_e *MockNotifier_Expecter) Send(ctx any, message any) *MockNotifier_Send_Call {
	return &MockNotifier_Send_Call{Call: _e.mock.On("Send", ctx, message)}
}

func (_c *MockNotifier_Send_Call) Run(run func(ctx context.Context, message notify.Message)) *MockNotifier_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 notify.Message
		if args[1] != nil {
			arg1 = args[1].(notify.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotifier_Send_Call) Return(v uint32, err error) *MockNotifier_Send_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockNotifier_Send_Call) RunAndReturn(run func(ctx context.Context, message notify.Message) (uint32, error)) *MockNotifier_Send_Call {
	_c.Call.Return(run)
	return _c
}
