// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nicholas-fedor/clankerwatch/internal/state"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockStore
func (_mock *MockStore) Load() (state.State, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 state.State
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (state.State, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() state.State); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(state.State)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockStore_Expecter) Load() *MockStore_Load_Call {
	return &MockStore_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockStore_Load_Call) Run(run func()) *MockStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Load_Call) Return(state1 state.State, err error) *MockStore_Load_Call {
	_c.Call.Return(state1, err)
	return _c
}

func (_c *MockStore_Load_Call) RunAndReturn(run func() (state.State, error)) *MockStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockStore
func (_mock *MockStore) Save(current state.State) error {
	ret := _mock.Called(current)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(state.State) error); ok {
		r0 = returnFunc(current)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - current state.State
func (_e *MockStore_Expecter) Save(current any) *MockStore_Save_Call {
	return &MockStore_Save_Call{Call: _e.mock.On("Save", current)}
}

func (_c *MockStore_Save_Call) Run(run func(current state.State)) *MockStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 state.State
		if args[0] != nil {
			arg0 = args[0].(state.State)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_Save_Call) Return(err error) *MockStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Save_Call) RunAndReturn(run func(current state.State) error) *MockStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
