// Copyright (c) Nicholas Fedor 2026 <nick@nickfedor.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/clankerwatch/internal/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDemoer creates a new instance of MockDemoer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDemoer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDemoer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDemoer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDemoer is an autogenerated mock type for the Demoer type
type MockDemoer struct {
	mock.Mock
}

type MockDemoer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDemoer) EXPECT() *MockDemoer_Expecter {
	return &MockDemoer_Expecter{mock: &_m.Mock}
}

// Demo provides a mock function for the type MockDemoer
func (_mock *MockDemoer) Demo(ctx context.Context, cfg config.Config) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Demo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.Config) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDemoer_Demo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Demo'
type MockDemoer_Demo_Call struct {
	*mock.Call
}

// Demo is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg config.Config
func (_e *MockDemoer_Expecter) Demo(ctx any, cfg any) *MockDemoer_Demo_Call {
	return &MockDemoer_Demo_Call{Call: _e.mock.On("Demo", ctx, cfg)}
}

func (_c *MockDemoer_Demo_Call) Run(run func(ctx context.Context, cfg config.Config)) *MockDemoer_Demo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.Config
		if args[1] != nil {
			arg1 = args[1].(config.Config)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDemoer_Demo_Call) Return(err error) *MockDemoer_Demo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDemoer_Demo_Call) RunAndReturn(run func(ctx context.Context, cfg config.Config) error) *MockDemoer_Demo_Call {
	_c.Call.Return(run)
	return _c
}
